version: '3'
services:
  phabricator:
    image: phabricator/phabricator
    ports:
      - 8888:80
    links:
      - db
      - smtp
    volumes:
       - config:/var/www/phabricator/conf
       - files:/var/www/files
  daemon:
    image: phabricator/daemon
    links:
      - db
      - smtp
    volumes:
       - config:/var/www/phabricator/conf
       - files:/var/www/files
  db:
    image: davidbarratt/phabricator-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
  # migrate:
  #   image: node:10
  #   env_file:
  #     - .env
  #   command: "tail -f /dev/null"
  #   working_dir: /app
  #   volumes:
  #     - ./:/app:cached
volumes:
  config:
  files:
  database:
